version: '3.8'

services: 
  db:
    image: mariadb:10.4
    container_name: calligo-dev-db
    restart: unless-stopped

    ports:
      - 3306:3306
  
    volumes:
      - ./data/mariadb:/var/lib/mysql
  
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb

    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  app:
    container_name: calligo-dev-app

    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile

    depends_on:
      - db
      
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    
    volumes:
      - ../:/workspace:cached
      - ../:/var/www/html
      - ../docker/etc/apache2/sites-available:/etc/apache2/sites-available

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  
volumes:
  mariadb-data:
    # driver: local
  # site:
    # driver: local
    # driver_opts:
    #   device: ../:/var/www/html
